---
hide_body: false
is_partial: false
fields:
- name: layout
  label: Layout
  type: text
  hidden: false
  default: default
- name: author
  label: Author
  type: text
  hidden: false
  default: The Bakery
